[package]
name = "advance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
atty = "0.2"

[dev-dependencies]
tokio = { version = "1.17", features = ["full"] } 
